### ISSUE TITLE
Implement Help Menu (popup window)

### ISSUE THREAD

**Issue by andreicozma1** [andreicozma1/STEM#27]

**Comment by hunterprice04** [comment]
@andreicozma1 I'm working on a layout for how the help menu is going to look. Please give some comments and your input on what I have so far. The goal is to answer any possible questions about the program most concisely and clearly.
https://docs.google.com/drawings/d/1WQAEOHAWPgNZG4R1q5Q8Oaf24x2PL3RFOM-zVZMT6IA/edit?usp=sharing

**Comment by hunterprice04** [comment]
@andreicozma1  I was thinking the best way to implement this help menu is through HTML. Javafx has a nice WebView object that we could use to display the HTML.
https://docs.oracle.com/javase/8/javafx/api/javafx/scene/web/WebView.html
let me know your thoughts?
